version: '3.7'

services:
  web:
    build: ./app
    command: gunicorn billing.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
#    env_file:
#      - ./app/.env.dev
    depends_on:
      - db

  db:
    image: postgres:11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=billing

  nginx:
    build: ./nginx
    ports:
      - 1234:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: