# Generated by Django 3.0.4 on 2020-03-04 12:34

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfer', '0002_auto_20200304_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_changed_at', models.DateTimeField(auto_created=True, auto_now=True)),
                ('balance_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('GBP', 'Pound Sterling'), ('RUB', 'Russian Ruble'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3)),
                ('balance', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet',
            },
        ),
        migrations.AlterField(
            model_name='moneytransfer',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receivers', to='transfer.Wallet'),
        ),
        migrations.AlterField(
            model_name='moneytransfer',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='senders', to='transfer.Wallet'),
        ),
        migrations.DeleteModel(
            name='UserBalance',
        ),
    ]
